# Generated by Django 3.1.12 on 2025-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('intitule', models.TextField()),
                ('fichier', models.FileField(upload_to='projets/')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
