# Generated by Django 3.1.12 on 2025-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commentaire_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('in-progress', 'En cours')], default='pending', max_length=20),
        ),
    ]
